services:
  servidor:
    build:
      context: .
      dockerfile: servidor.Dockerfile
    ports:
      - "9090:9090"
      #- "22:22"
    networks:
      - app-network
    volumes:
      - ./servidor/postos.json:/app/postos.json
      - ./servidor/veiculos.json:/app/veiculos.json
    restart: unless-stopped

  cliente-posto:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: cliente-posto.Dockerfile
    ports:
      - "8081:8081"
      #- "22:22"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo
    restart: unless-stopped

  cliente-posto-um:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: cliente-posto.Dockerfile
    ports:
      - "8085:8085"
      #- "22:22"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo
    restart: unless-stopped

  cliente-veiculo-um:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: cliente-veiculo.Dockerfile
    ports:
      - "8082:8082"
      #- "22:22"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo
    restart: unless-stopped    

  cliente-veiculo-dois:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: cliente-veiculo.Dockerfile
    ports:
      - "8083:8083"
      #- "22:22"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo
    restart: unless-stopped 


  cliente-veiculo-tres:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: cliente-veiculo.Dockerfile
    ports:
      - "8084:8084"
      #- "22:22"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo
    restart: unless-stopped 

networks:
  app-network:
    driver: bridge
