services:
  servidor:
    build:
      context: .
      dockerfile: servidor.Dockerfile
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - ./servidor/postos.json:/app/postos.json
      - ./servidor/veiculos.json:/app/veiculos.json
    restart: unless-stopped

  cliente-posto:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: cliente-posto.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo
    restart: unless-stopped

  cliente-veiculo:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: cliente-veiculo.Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
