services:
  servidor:
    build:
      context: .
      dockerfile: servidor.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./modelo:/app/modelo

  cliente:
    build:
      context: .
      dockerfile: cliente.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - servidor
    volumes:
      - ./modelo:/app/modelo

networks:
  app-network:
    driver: bridge
